# Version of the docker-compose syntax
version: "3.9"

# Services
# docker-compose can consist of 1 or more services
services:
  app:
    build:
      # Where is the dockerfile
      context: .
      args:
        - DEV=true
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
    command:
      # This is used when "docker-compose up" is called
      # This is overrided by "docker-compose run" command, eg docker-compose run --rm app sh -c "django-admin startproject app ."
      # This command is only used if no command is specified with "docker-compose run" or "docker-compose up" was called
      sh -c "python manage.py runserver 0.0.0.0:8000"
    environment:
     - DB_HOST=db
     - DB_NAME=devdb
     - DB_USER=devuser
     - DB_PASS=changeme
    depends_on:
      - db

  db:
    image: postgres:13-alpine
    volumes:
      - dev-db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=devdb
      - POSTGRES_USER=devuser
      - POSTGRES_PASSWORD=changeme

# Volumes
volumes:
  dev-db-data:
